// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestVR.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class VerifyTheContactFormFieldsFeature : object, Xunit.IClassFixture<VerifyTheContactFormFieldsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Contact.feature"
#line hidden
        
        public VerifyTheContactFormFieldsFeature(VerifyTheContactFormFieldsFeature.FixtureData fixtureData, TestVR_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Verify the contact form fields", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
  #line hidden
#line 4
    testRunner.Given("the verisk contact page open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="The mandatory field has *")]
        [Xunit.TraitAttribute("FeatureTitle", "Verify the contact form fields")]
        [Xunit.TraitAttribute("Description", "The mandatory field has *")]
        [Xunit.InlineDataAttribute("Name", "Name *", new string[0])]
        [Xunit.InlineDataAttribute("Company", "Company *", new string[0])]
        [Xunit.InlineDataAttribute("Job Title", "Job Title *", new string[0])]
        [Xunit.InlineDataAttribute("Email address", "Email address *", new string[0])]
        [Xunit.InlineDataAttribute("Phone number", "Phone number *", new string[0])]
        [Xunit.InlineDataAttribute("Message", "Message *", new string[0])]
        [Xunit.InlineDataAttribute("Enquiry Type", "Enquiry Type *", new string[0])]
        [Xunit.InlineDataAttribute("Subscribing", "By subscribing to this, you are consenting to Verisk processing your personal inf" +
            "ormation for the purpose of providing updates in relation to products and servic" +
            "es that may be of interest. We will store this data until such time as you ask u" +
            "s to stop.", new string[0])]
        [Xunit.InlineDataAttribute("Recaptcha", "Recaptcha *", new string[0])]
        public void TheMandatoryFieldHas(string element, string text, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("text", text);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The mandatory field has *", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
  this.FeatureBackground();
#line hidden
#line 8
    testRunner.Then(string.Format("the {0} is shown in contact page", element), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
    testRunner.And(string.Format("the {0} has the text {1} in contact", element, text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                VerifyTheContactFormFieldsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                VerifyTheContactFormFieldsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
