version: '3.7'
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
  chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
  firefox:
    image: selenium/node-firefox
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
