name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Browser: [chrome, firefox]
        Mode: ["headless", "remote"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run selenium grid
        if: ${{ matrix.Mode }} == "remote"
        run: |
          docker-compose up --scale chrome=2 --scale firefox=2 -d
          chmod +x ./wait_for_grid.sh
          ./wait_for_grid.sh
      - name: Test ${{matrix.Browser}}
        run: dotnet test --no-build --verbosity normal -e BROWSER=${{matrix.Browser}} -e MODE=${{matrix.Mode}} --logger "trx;LogFileName=test-results-${{matrix.Plan}}.trx"
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: TestResults/*
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-images
          path: bin/Debug/*/Screenshots/*
