name: "Test Report"
on:
  workflow_run:
    workflows: ["CI-WINDOWS", "CI-UBUNTU"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Dotnet Tests
          path: "*.trx"
          reporter: dotnet-trx
